version: '2'
services:
  fluentbit:
    image: fluent/fluent-bit:1.3
    command: /fluent-bit/bin/fluent-bit -i cpu -p 'tag=fluent.bit' -o forward://fluentd:12225
    networks:
      efk:

  fluentd:
    build: ./fluentd
    image: fluentd-es:1.8-1
    volumes:
      - ./fluentd:/etc/fluentd
    command: -c /etc/fluentd/in-fluent_bit.conf -v
    networks:
      efk:
        aliases:
          - fluentd
 
  elasticsearch:
    image: elasticsearch:7.5.1
    environment:
      - discovery.type=single-node
    networks:
      efk:
        aliases:
          - elasticsearch

  kibana:
    image: kibana:7.5.1
    ports:
      - "5601:5601"
    networks:
      efk:
 
networks:
  efk: